### PR TITLE
fix: adjust webpack rspack hooks sequence

### PR DESCRIPTION
**Pull request by qiYuei**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

webpack | Rspack, The load hook should be executed earlier than the transform hook

I'm not sure if I'm doing this as a Breaking change

image

[minimal reproduction](https://github.com/qiYuei/deef-webpack)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by antfu** [comment]
It seems to make sense. Possible to add some tests to it?

**Comment by qiYuei** [comment]
okay,I try to write it.But there seems to be something wrong with the rspack in my environment😅.I'll fill in the Rspack test cases later

**Comment by qiYuei** [comment]
@antfu  hello,I have submitted the test files, please check it!😁

**Comment by qiYuei** [comment]
@antfu    Can this be merged? Or what else do I need to change 🧐

**Comment by easonsolov** [comment]
hi,I have been using unplugin recently and have encountered the same issue with a plugin. Is there any progress with this PR? Or is this a bug that belongs to unplugin? thanks @antfu @sxzz

**Pull request merged**
