### PR TITLE
Addressing some issues

### PR DESCRIPTION
**Pull request by TropicalRaisel**
- Updated dependencies (`pnpm ncu` to check and `pnpm ncu -u` to upgrade, then `pnpm i`)
- Added an ESLint fix script
- Added a solution to #13

### CODE REVIEW

**Comment by antfu** [comment]
Please don't do deps bumping and fixes in a single PR. Can you separate them into two? Thanks

**Comment by TropicalRaisel** [comment]
Is there a way to do so w/out closing this PR, or do two new PRs need to be opened?

**Comment by TropicalRaisel** [comment]
It just feels like it'll be more work than it's worth honestly. All tests that were passing before these changes are passing. Naturally that means it builds successfully as well. I'll keep that in mind for any future PRs though! If you close this PR I'll do things incrementally.

**Comment by antfu** [comment]
- When merging, each PR will be presented as a single commit and been used for generating docs. Having multiple things in one commit will make the changelog harder
- Have multiple things is also risky for your PR to be merged and the maintainer to accepts it. As we might only want part of the changes.
- Dependencies changes are verbose and made it hard to find the code of fix

In this case, we use `yarn` intentionally to align with Nuxt's ecosystem. Please also ask before you made the tooling switch for example to `pnpm`.

**Comment by TropicalRaisel** [comment]
Thank you for explaining!

**Pull request closed without merging**
