### PR TITLE
fix: resolveId missing options type

### PR DESCRIPTION
**Pull request by 1247748612**
The option type is currently missing, it actually exists.
I need to use isEntry property

### CODE REVIEW

**Comment by 1247748612** [comment]
@antfu cc

**Comment by antfu** [comment]
I think the type was intentionally narrowed down to prevent relying on APIs from Rollup that are not compatible with other bundlers.

**Comment by 1247748612** [comment]
you're right.

but the isEntry property in Rollup is very useful and commonly used, what should I do?
Or I add the "undefined" type in the "options",  is it ok?

**Comment by antfu** [comment]
You can use https://github.com/unjs/unplugin#framework-specific-logic

**Comment by 1247748612** [comment]
Thank you!

This would work, but would cause code duplication as I would implement different bundler logic in resolveId and the `framework specific logic` would have me split resolveId's code.

**Pull request closed without merging**
